### ISSUE TITLE
Create module for JUnit 5 support

### ISSUE THREAD

**Issue by lordofthejars** [SpectoLabs/hoverfly-java#121]
Create module for JUnit 5 support, so Hoverfly can be used as Rule or JUnit 5 Module.

Currently working on that. PR coming in next days/week

**Comment by lordofthejars** [comment]
[WiP]

**Comment by Sandmania** [comment]
I'm thinking about moving a project from JUnit4 + MockServer based tests to JUnit5 + Hoverfly. I was wondering if this feature is on the roadmap any time soon?

**Comment by tommysitu** [comment]
Hi @Sandmania, I should be able to review @lordofthejars PR and get this feature out ASAP given that JUnit 5 has finally released. Any input is appreciated.

**Comment by lordofthejars** [comment]
I'd say that final release might changed something from extension API point
of view

**Comment by tommysitu** [comment]
@lordofthejars have you had experienced with multi-projects release using Gradle? I guess I need to create a new project on Sontype repo and the existing `build.gradle` should be able to handle it, right?

**Comment by lordofthejars** [comment]
No, sorry

El dl., 16 d’oct. 2017 a les 18:15, Tommy Situ (<notifications@github.com>)
va escriure:

**Comment by tommysitu** [comment]
@Sandmania, hoverfly-java-junit5 is now released. You should be able to get it from [Maven repo](https://search.maven.org/#artifactdetails%7Cio.specto%7Choverfly-java-junit5%7C0.9.0%7Cjar) into your project. Documentation can be found [here](http://hoverfly-java.readthedocs.io/en/latest/pages/junit5/junit5.html). 
@lordofthejars your contributions have made this happened, thank you!
