### ISSUE TITLE
Upstream Proxy Settings

### ISSUE THREAD

**Issue by shivrajdalu** [SpectoLabs/hoverfly-java#138]
there does not appear to be any way to set up upstream proxy in "hoverfly-java" as given in the link below 
[https://docs.hoverfly.io/en/stable/pages/tutorials/advanced/behindaproxy/behindaproxy.html](url)
please help

**Comment by tommysitu** [comment]
Hoverfly supports upstream proxy settings, but it is not added to Hoverfly-Java yet. It should be an easy fix. If you are interested in contributing to open source project, you're welcome to submit a PR.

**Comment by tommysitu** [comment]
This will be available in v0.9.3
