### ISSUE TITLE
The specified schemaVersion is ignored

### ISSUE THREAD

**Issue by MatousJobanek** [SpectoLabs/hoverfly-java#158]
If the `schemaVersion` is specified in simulation config, then it is ignored and used the [hard-coded](https://github.com/SpectoLabs/hoverfly-java/blob/master/src/main/java/io/specto/hoverfly/junit/core/model/HoverflyMetaData.java#L27) one.

**Comment by tommysitu** [comment]
Fixed by v0.10.0
