### ISSUE TITLE
When configuring hoverfly, it should be clear if it is remote or local

### ISSUE THREAD

**Issue by MatousJobanek** [SpectoLabs/hoverfly-java#160]
Currently, the `HoverflyConfig` API has only one static method `configs` that returns `LocalHoverflyConfig` instance. Then, if I want to use remote access, I need to call `remote()`, but nothing from the previous setup is set in the `RemoteHoverflyConfig`. Consider this code:
```java
HoverflyConfig.configs()
                .captureHeaders("Authorization")
                .destination(destination)
                .proxyPort(port)
                .remote();
```
Then I would expect that the proxy port and other config params are used in the remote connection, but they are not as the `RemoteHoverflyConfig` is [created](https://github.com/SpectoLabs/hoverfly-java/blob/master/src/main/java/io/specto/hoverfly/junit/core/HoverflyConfig.java#L148) without any parameters.

So I think that it should be clear from the very beginning if it is a remote or local config, so the API could look like this:
```java
HoverflyConfig.localConfigs()
HoverflyConfig.remoteConfigs()
```

**Comment by tommysitu** [comment]
It is a bit confusing. I'll look into your PRs in the evening. Thanks!
