### ISSUE TITLE
Options matcher

### ISSUE THREAD

**Issue by s-spindler** [SpectoLabs/hoverfly-java#163]
At the moment `StubServiceBuilder` allows matching GET, PUT, POST, DELETE and PATCH requests as well as `anyMethod`.

I am writing a test that needs to check if CORS requests are proxied correctly by an API gateway service. For that I need to match on OPTIONS.

It would be great if the missing HTTP methods could be added:
OPTIONS, CONNECT, HEAD

**Comment by tommysitu** [comment]
@s-spindler, that would be a straight-forward change. Feel free to submit a PR if you'd like to contribute.

**Comment by tommysitu** [comment]
I've fixed this in release 0.10.1.
