### ISSUE TITLE
Test fail in Jenking

### ISSUE THREAD

**Issue by naman90** [SpectoLabs/hoverfly-java#177]
I get the following error when jenkins is building project and run test cases.

`13:58:25.058 [main] INFO io.specto.hoverfly.junit.core.TempFileManager - Selecting the following binary based on the current operating system: hoverfly_linux_amd64
13:58:25.062 [main] INFO io.specto.hoverfly.junit.core.TempFileManager - Storing binary in temporary directory /tmp/hoverfly.1856279864141179710/hoverfly_linux_amd64
13:58:25.162 [main] INFO io.specto.hoverfly.junit.core.Hoverfly - Executing binary at /tmp/hoverfly.1856279864141179710/hoverfly_linux_amd64
13:58:25.227 [main] DEBUG org.zeroturnaround.exec.ProcessExecutor - Executing [/tmp/hoverfly.1856279864141179710/hoverfly_linux_amd64, -db, memory, -pp, 42681, -ap, 46601] in /tmp/hoverfly.1856279864141179710.
13:58:25.235 [main] ERROR org.zeroturnaround.exec.ProcessExecutor - Could not start process:
java.io.IOException: Cannot run program "/tmp/hoverfly.1856279864141179710/hoverfly_linux_amd64" (in directory "/tmp/hoverfly.1856279864141179710"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)`

**Comment by tommysitu** [comment]
That's interesting. Does it fail on your local machine? Which version of Hoverfly-java are you using?

**Comment by naman90** [comment]
It doesn't fail on local windows and linux machines. It is failing in a job running inside jenkins pipeline. 
Hoverfly java Version- 0.9.1. May be there are executable permission issues?

**Comment by tommysitu** [comment]
It sounds very likely to be executable permission issue, as it didn't fail at copying the binary.

**Comment by tommysitu** [comment]
It might be related to this one: https://github.com/jenkinsci/docker/issues/422, you can try out some of the suggestions there, like changing the tmp folder location

**Comment by tommysitu** [comment]
Hi @naman90 please re-open this issue if you are still having the problem.
