### ISSUE TITLE
Invalid Http response

### ISSUE THREAD

**Issue by mlundela** [SpectoLabs/hoverfly-java#179]
It seems to be an issue using `@ClassRule` with _https_. If I run more than one test, then one of them will fail with the following exception:

    Caused by: java.io.IOException: Invalid Http response
	  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1606)
	  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	  at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	  at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	  at com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(URLConnectionClientHandler.java:253)
	... 34 more

If I change the protocol to be _http_ then the problem disappears.

Using `@Rule` instead of `@ClassRule` is another work around, but brings additional overhead.

**Comment by mlundela** [comment]
simulation.json:

    {
    "data": {
      "pairs": [
        {
          "request": {
            "method": {
              "exactMatch": "GET"
            },
            "destination": {
              "exactMatch": "reqres.in"
            }
          },
          "response": {
            "status": 200
          }
        }
      ],
      "globalActions": {
        "delays": []
      }
    },
    "meta": {
      "schemaVersion": "v4"
    }
    }

Test code:

    package no.dnb.outputmanagement.archiveservice2.service;
    
    import io.specto.hoverfly.junit.rule.HoverflyRule;
    import org.junit.Before;
    import org.junit.ClassRule;
    import org.junit.Test;
    import org.springframework.web.client.RestTemplate;
    
    public class HoverflyTest {
    
        @ClassRule
        public static HoverflyRule hoverflyRule = HoverflyRule.inCaptureOrSimulationMode("simulation.json");
    
        private RestTemplate restTemplate;
    
        @Test
        public void get1() {
            restTemplate.getForEntity("https://reqres.in/api/products/1", String.class);
        }
    
        @Test
        public void get2() {
            restTemplate.getForEntity("https://reqres.in/api/products/2", String.class);
        }
    
        @Before
        public void before() {
            restTemplate = new RestTemplate();
        }
    }

**Comment by tommysitu** [comment]
@mlundela this bug is introduced from the Hoverfly 0.16.0 release, and it is related to this issue: https://github.com/SpectoLabs/hoverfly/issues/727. 
Please use Hoverfly-java v0.10.0 for the time being. I'll let you know when a fix is available.

**Comment by tqh** [comment]
Getting the same error even after switching to 0.10.0 seems to select a broken binary anyway. 
```
15:28:20.995 INFO  core.TempFileManager {} - Selecting the following binary based on the current operating system: hoverfly_OSX_amd64
15:28:20.998 INFO  core.TempFileManager {} - Storing binary in temporary directory /var/folders/vy/2sc8qjd505q_ysf0nt5ddzdc0000gn/T/hoverfly.18046264787722427359/hoverfly_OSX_amd64

```

**Comment by tommysitu** [comment]
@tqh I can run the above test and simulation using hoverfly-java 0.10.0 fine. I can see that it bundles with v0.15.0 hoverfly: 
```
tommys-mbp:hoverfly.7605882124662211737 tommysitu$ ./hoverfly_OSX_amd64 -version
v0.15.0
```
Perhaps you are having other issues? What's the test you are running, and what error do you get?

**Comment by tqh** [comment]
It only fails when querying another path before. Preparing test case...

**Comment by tqh** [comment]
```
{
  "data" : {
    "pairs" : [ {
      "request" : {
        "path" : {
          "exactMatch" : "/long/path/1"
        },
        "method" : {
          "exactMatch" : "GET"
        },
        "destination" : {
          "exactMatch" : "other.internal"
        },
        "scheme" : {
          "exactMatch" : "https"
        },
        "query" : {
          "exactMatch" : ""
        },
        "body" : {
          "exactMatch" : ""
        }
      },
      "response" : {
        "status" : 200,
        "body" : "{ \"complex\": \"json object\"}",
        "encodedBody" : false,
        "templated" : false,
        "headers" : {
          "Content-Type" : [ "application/json" ]
        }
      }
    }, {
      "request" : {
        "path" : {
          "exactMatch" : "/long/path/test/caseA/1"
        },
        "method" : {
          "exactMatch" : "GET"
        },
        "destination" : {
          "exactMatch" : "other.internal"
        },
        "scheme" : {
          "exactMatch" : "https"
        },
        "query" : {
          "exactMatch" : ""
        },
        "body" : {
          "exactMatch" : ""
        }
      },
      "response" : {
        "status" : 404,
        "encodedBody" : false,
        "templated" : false
      }
    }, {
      "request" : {
        "path" : {
          "exactMatch" : "/long/path/test/caseB/1"
        },
        "method" : {
          "exactMatch" : "GET"
        },
        "destination" : {
          "exactMatch" : "other.internal"
        },
        "scheme" : {
          "exactMatch" : "https"
        },
        "query" : {
          "exactMatch" : ""
        },
        "body" : {
          "exactMatch" : ""
        }
      },
      "response" : {
        "status" : 204,
        "encodedBody" : false,
        "templated" : false
      }
    } ],
    "globalActions" : {
      "delays" : [ ]
    }
  },
  "meta" : {
    "schemaVersion" : "v4"
  }
}

```
And running
```
hoverctl import sim.txt
curl -k --proxy http://localhost:8500 -v https://other.internal/long/path/1
```
Always returns:
```
< HTTP/1.1 200
< Content-Length: 27
< Content-Type: application/json
< Transfer-Encoding: chunked
```
However it only fails if calling `/long/path/test/caseB/1` before. It is with java JerseyClient, os maybe it is something with keep alives.

**Comment by tqh** [comment]
Setting `System.setProperty("http.keepAlive", "false");` makes it go away.

**Comment by tommysitu** [comment]
@mlundela, the Hoverfly-Java v0.11.0 release is available. It should fix the bug you raised.

**Comment by tommysitu** [comment]
@tqh From what I see, it seems to be a different bug, I will create a new issue for that.

**Comment by tommysitu** [comment]
@tqh actually it is a related issue. It would break some HTTP clients if the response contains both Transfer-Encoding and Content-Length headers. Upgrading to Hoverfly-Java 0.11.0 should fix it.
