### ISSUE TITLE
Can not simulate localhost

### ISSUE THREAD

**Issue by ChaiZhi** [SpectoLabs/hoverfly-java#188]
I am trying to simulate the host `localhost:8080` and it didn't work
```
I/O error on GET request for "http://localhost:8080/": Connection refused
```

**Comment by tommysitu** [comment]
@ChaiZhi have you try using this config:` localConfigs().proxyLocalHost()`
You can find all the config options here: https://hoverfly-java.readthedocs.io/en/latest/pages/corefunctionality/configuration.html

**Comment by ChaiZhi** [comment]
@tommysitu Thank you very much, I miss this option when reading the document
