### ISSUE TITLE
Control what hoverfly captures or simulates

### ISSUE THREAD

**Issue by tommysitu** [SpectoLabs/hoverfly-java#19]
HoverflyRule by default starts up Hoverfly and set it as JVM default proxy. This will block HTTP traffic to those non-registered remote APIs. Tests that require both stub and real services will not function.

HoverflyRule should probably support the Hoverfly destination filtering to control what it captures or simulates:
https://docs.hoverfly.io/en/latest/pages/keyconcepts/destinationfiltering.html

**Comment by tommysitu** [comment]
@simomo, this fix should solve your spring cloud config issue. It will be released as v0.4.3. If you want to play around with it for now, you can try out the `0.4.3-SNAPSHOT` version by including this in your build.gradle: 
```
repositories {
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots'
    }
}
```
Your hoverfly rule should provide the destination settings to only process requests to that hostname: 
```
@ClassRule
public static HoverflyRule hoverflyRule = HoverflyRule.inSimulationMode(SimulationSource.dsl(
            service("www.test.com")
            .get("/")
            .willReturn(success(HttpBodyConverter.json("{}")).withDelay(10, TimeUnit.SECONDS))
    ), configs().destinaton("www.test.com"));
```

**Comment by simomo** [comment]
@tommysitu  many thanks ! 
I will try this snapshot.
When will v0.4.3 release? 

And I also learned about this fix,  it looks like hoverfly-java sends a hoverflyInfo structure to hoverfly proxy deamon to config it.
I'm curious about that: this hoverflyInfo is a new type, but I don't see corresponding changes in hoverfly deamon project(https://github.com/SpectoLabs/hoverfly).

Million thanks for your support! It helps me a lot~

**Comment by tommysitu** [comment]
@simomo, it should be released today. 

Hoverfly already supports these endpoints for configurations: 
https://docs.hoverfly.io/en/latest/pages/reference/api/api.html#get-api-v2-hoverfly
That's right there is no change on the hoverfly project. 

Are you interested in contributing?

**Comment by simomo** [comment]
@tommysitu ,  I have switched the version to `0.4.3`, it works good :)  Thank you!

I would like to contribute to hoverfly :) it's a great opportunity for me ~ 
Where should I start?  I've read the `[contributing page]` (https://docs.hoverfly.io/en/latest/pages/contributing.html)

**Comment by tommysitu** [comment]
@simomo, that's cool. You can find all the issues in this page: https://github.com/SpectoLabs/hoverfly-java/issues
Issue 82 and 67 is a good starting point.

Once you picked an issue you'd like to work on, you need to fork the project to your github account, work on your own branch. When you are done,  create a pull request to merge into the original master branch. One of us will review it. 

Feel free to comment on the issue if you have questions. Thank you!
