### ISSUE TITLE
0.12.0 release?

### ISSUE THREAD

**Issue by ttiurani** [SpectoLabs/hoverfly-java#190]
We're very happy Hoverfly users, but would very much like to get a release with a newer hoverfly binary that uses the new matcher syntax. We've been in two worlds for quite a while with our integration tests using the `"matcher": "exact"` syntax, but unit tests the `"exactMatch":` syntax. Also the new multiple simulation file support would be excellent.

Thanks again for the great project!

**Comment by tommysitu** [comment]
Hi @ttiurani. I know, it has been a while. That's why I have started to work on the new release again this week. At the moment, I am just gonna finish the patch release for hoverfly first, and then will bring Hoverfly-java up-to-date.

**Comment by tommysitu** [comment]
You can try out the version 0.11.1 later once it's available on Maven Central.

**Comment by tommysitu** [comment]
It usually takes a day to show up on Maven Central.
