### ISSUE TITLE
HoverflyRule/HoverflyExtension: Provide Support for Pre-Processing Simulation

### ISSUE THREAD

**Issue by mmichaelis** [SpectoLabs/hoverfly-java#193]
As stated in a todo comment in [HoverflyRule](https://github.com/SpectoLabs/hoverfly-java/blob/5a7af569259529bc402c30de439be0759c5e9742/src/main/java/io/specto/hoverfly/junit/rule/HoverflyRule.java#L313) it would be great, if you may modify the Simulation right before it is handed over to hoverfly client. For HoverflyExtension this would be before executing [line 112](https://github.com/SpectoLabs/hoverfly-java/blob/42b940412beb67968508c7fccaf7bed8dda249b1/junit5/src/main/java/io/specto/hoverfly/junit5/HoverflyExtension.java#L112)

One example where I could have used this is a workaround for SpectoLabs/hoverfly#792. As you see in the example, the current approach is quite complex - and the Simulation object is handed over twice to the Hoverfly client by this solution.

Another example would be to be able in general to either extend the Simulation as suggested by the todo comment in `HoverflyRule` or to weaken matching criteria of the captured data on the fly (without the need to manually edit the captured data after each capturing process).

While this issue is not about reducing the complexity it is about preventing duplicate simulation processing in client - and providing a clean extension point.

Suggested API (JUnit 5):

```java
@HoverflySimulate(
        enableAutoCapture = true,
        config = @HoverflyConfig(
                simulationPreProcessor = MyTest.CustomPreProcessor.class
        )
)
class MyTest {
  static class CustomPreProcessor extends SimulationPreProcessor {
    public void accept(Simulation simulation) {
     }
  }
}
```

where again the `SimulationPreProcessor` interface either extends `java.util.function.Consumer` if the simulation is considered mutable, or `java.util.function.Function` if the simulation shall be considered immutable.

If implemented, the next obvious task is to ease Simulation pre-processing. Currently most of the Simulation despite the stored collections are immutable (providing no setters). But that is another story 😄

**Comment by mmichaelis** [comment]
I am currently looking if I could implement such a configuration option (for JUnit 4 as well as for JUnit 5). Unfortunately, I am not sure, if I understand the difference between remote and local configuration correctly. Will such a pre-processor only be part of a local configuration? Or is it valid for both remote as well as local configuration?

Regarding the suggested implementation, I would start with a `Consumer`, as it seems challenging to change the Simulation to an immutable object as this also requires to provide some API to create modified clones from an existing Simulation. Do you have any objections?

**Comment by tommysitu** [comment]
Your original issue https://github.com/SpectoLabs/hoverfly/issues/792 is a bug, but `SimulationPreProcessor` is a really good idea, it will benifit the scenario when you want to transform some captured data programmatically. 

A PreProcessor will be run before hoverfly importing the source as you have pointed out. It has nothing to do with the local or remote configs of which sole purposes are to set up the flags for executing the binary and the HoverflyClient. 

I don't have objection to making Simulation mutable especially when we have a use case for doing that. It wasn't probably immutable anyway.

**Comment by mmichaelis** [comment]
Done with #201.

**Comment by tommysitu** [comment]
Documentation: https://github.com/SpectoLabs/hoverfly-java/pull/204
