### ISSUE TITLE
Store recorded data under default hoverfly directory

### ISSUE THREAD

**Issue by tommysitu** [SpectoLabs/hoverfly-java#20]
Given the following HoverflyRule:
```
@Rule
    public HoverflyRule hoverflyRule = HoverflyRule.inCaptureMode("recorded-simulation.json");
```
The recorded json file will be saved in the `test/resources/` folder. There is a risk of overriding existing file if it has the same name. 

It'd be better to save recorded json file into a root directory such as `test/resources/hoverfly/`.

**Comment by lordofthejars** [comment]
Working on this. PR in next minutes.

**Comment by lordofthejars** [comment]
The only problem I see is that it breaks back the compatibility. But I am planning to add a parameter in `config()` so you can set the output directory, so any users can migrate easily by just configuring to `src/test/resources`

**Comment by mogronalol** [comment]
@lordofthejars Sounds good, I wouldn't worry about it being a breaking change.
