### ISSUE TITLE
Hoverfly with Junit5 and WebTestClient doesn't capture request and response

### ISSUE THREAD

**Issue by amangarg4804** [SpectoLabs/hoverfly-java#210]
## Description of the bug
Hoverfly with Junit5 and WebTestClient doesn't capture request and response

## Context information (for bug reports)
What you were doing

## Steps to reproduce the issue

1. Add following dependency in pom.xml
```
        <dependency>
            <groupId>io.specto</groupId>
            <artifactId>hoverfly-java-junit5</artifactId>
            <version>0.11.5</version>
            <scope>test</scope>
        </dependency>
```
2. Annotate test class with 
```
@HoverflyCapture(path = "../resources/hoverfly",
        filename = "captured-simulation.json",
        config = @HoverflyConfig(captureAllHeaders = true, proxyLocalHost = true))
```
3. Make HTTP requests using WebTestClient provided by spring. Doesn't Work!!
4. Make HTTP requests using TestRestTemplate provided by Spring. Works fine!!

### Observed result
Hoverfly is able to capture request and response if I use org.springframework.boot.test.web.client.TestRestTemplate instead of org.springframework.test.web.reactive.server.WebTestClient

### Expected result
Hoverfly should be able to capture request and response when using org.springframework.test.web.reactive.server.WebTestClient

**Comment by tommysitu** [comment]
@amangarg4804 It's likely that WebTestClient doesn't use the default JAVA system proxy. I will try it out and let you know.

**Comment by amangarg4804** [comment]
@tommysitu Thank you. I will wait for your response.

**Comment by tommysitu** [comment]
@amangarg4804 I think it's related to this issue: https://github.com/SpectoLabs/hoverfly-java/issues/185. 

The only difference is the previous issue uses `WebClient` and you are using `WebTestClient`. But I guess both don't use default SSLContext, and you will need to configure it.

Please have a look at that issue and try out the suggestions.

**Comment by tommysitu** [comment]
Closing because it's a duplicated issue of #185
