### ISSUE TITLE
Auto-JSON marshalling when building request/response body using DSL

### ISSUE THREAD

**Issue by tommysitu** [SpectoLabs/hoverfly-java#22]
If the HoverflyRule DSL can automatically marshal/ unmarshal request/response content based on `Content-Type` header, that will be a massive advantage. So instead of 

```
.willReturn(response()
     .status(200)
     .body("{\"bookingId\":\"1\",\"origin\":\"London\",\"destination\":\"Singapore\",\"time\":\"2011-09-01T12:30\",\"_links\":{\"self\":{\"href\":\"http://localhost/api/bookings/1\"}}}")
     .header("Content-Type", "application/json")
```

It could be simplified to this: 

```
.willReturn(response()
     .status(200)
     .body(bookingA)
     .header("Content-Type", "application/json")
```
where bookingA is a `Booking` object

**Comment by mogronalol** [comment]
Even more useful could be an overloaded wrapper around it, something like

`willReturn(json(bookingA))`
`willReturn(json("{\"bookingId\":\"1\",\"origin\":\"London\",\"destination\":\"Singapore\",\"time\":\"2011-09-01T12:30\",\"_links\":{\"self\":{\"href\":\"http://localhost/api/bookings/1\"}}}"))`

**Comment by mogronalol** [comment]
I'm going to lock this issue into JSON specifically and then leave it open for others in the future
