### ISSUE TITLE
<200,{"error":"Do: Invalid Id Hex","status_code":500,"status_text":"Internal Server Error"}

### ISSUE THREAD

**Issue by rajalekshmyrajesh** [SpectoLabs/hoverfly-java#221]
Hi Team,

Issue : <200,{"error":"Do: Invalid Id Hex","status_code":500,"status_text":"Internal Server Error"}

Getting the above response for all the request that I have tried using hoverfly java.  But the same request are working fine in postman. Can anyone help to resolve the issue.

Regards

Rajalekshmy

**Comment by tommysitu** [comment]
@rajalekshmyrajesh please provide info on how to reproduce this error.

**Comment by tommysitu** [comment]
closing because of lack of info
