### ISSUE TITLE
How to trust Hoverfly programmatically instead of keytool ?

### ISSUE THREAD

**Issue by Amr1977** [SpectoLabs/hoverfly-java#228]
Please use: https://gitter.im/SpectoLabs/hoverfly for questions about `Hoverfly`.

Only posts that are bug reports or feature/enhancement requests will be addressed here.

**Comment by tommysitu** [comment]
Hoverfly-java does that for you automatically. Please post your question on  https://gitter.im/SpectoLabs/hoverfly if you need more help.
