### ISSUE TITLE
Capturing and simulating with two Hoverfly instances misbehaves

### ISSUE THREAD

**Issue by larsthorup** [SpectoLabs/hoverfly-java#229]
## Description of the bug

As described elsewhere (https://github.com/SpectoLabs/hoverfly/issues/864#issuecomment-559096554) we are using Hoverfly to auto-mock requests in service tests. We want to CAPTURE requests to the service-under-test while SIMULATING requests to external-services. It appears that Hoverfly does not (yet) support capturing and simulating through the same instance, so we are trying to orchestrate 2 Hoverfly instances. Starting them in either order gives different issues.

When starting Hoverfly first in Capture mode, then another instance in Simulate mode, the capture file ends up only including request/response-pairs from the interaction with the Hoverfly Admin end points. See https://github.com/larsthorup/hoverfly-capture-simulate/blob/master/src/test/java/com/example/hoverfly/HoverflyDemoApplicationIntegrationTests.java#L92

When starting Hoverfly first in Simulate mode, then another instance in Capture mode, the simulation is not taking effect, meaning that calls go through to the external service instead of being replayed. See https://github.com/larsthorup/hoverfly-capture-simulate/blob/master/src/test/java/com/example/hoverfly/HoverflyDemoApplicationIntegrationTests.java#L128

## Steps to reproduce the issue

Please checkout this repo with code to reproduce this issue:

* https://github.com/larsthorup/hoverfly-capture-simulate

The repo contains a small Spring Boot service (service-under-test) that invokes `time.jsontest.com` (external-service). The relevant part of the tests are linked above. Note, that the tests will *pass* to show that the issues described above have been reproduced.

### Observed result
Either simulate doesn't happen, or the relevant request isn't captured, as explained above.

### Expected result
Being able to simulate the external request to `time.jsontest.com` while simultaneously capturing the request to our own end-point `/service/time`.

## Additional relevant information
If not indicated above:
1. Hoverfly Java version: 0.12.2

**Comment by larsthorup** [comment]
I have extended the reproduction code with a new file https://github.com/larsthorup/hoverfly-capture-simulate/blob/master/src/test/java/com/example/hoverfly/HoverflyDemoApplicationExtensionIntegrationTests.java containing a test that uses Hoverfly.extensions instead of nested Hoverfly instances.

Again, this test passes as is, because Capture is not enabled. If you enable Capture by uncommenting the `@BeforeAll` and `@AfterAll` the Capture will work but the Simulate will no longer work and the tests will fail.

Is it possible to run Capture and Simulate via two Hoverfly instances at all? Should these examples work? Are there any work-arounds to make this work?

**Comment by larsthorup** [comment]
I think I found a work-around to make this work. I have pushed an update to the repo with the reproduction code: 

* https://github.com/larsthorup/hoverfly-capture-simulate/blob/master/src/test/java/com/example/hoverfly/HoverflyDemoApplicationIntegrationTests.java#L164

This is what I believe makes it work:

1) Starting the hoverflySimulate instance *last* means that this proxy is what will be used by the service-under-test when it makes requests to external-service, meaning that these requests will be simulated as expected.
2) Explicitly setting proxy settings for the request from the test to the service-under-test to make it use the hoverflyCapture instance, meaning that this request will be captured as expected.

Is this a good approach? Can we expect this to continue to work with future versions of Hoverfly and Hoverfly Java? Are there any drawbacks or caveats that we should be aware of?

**Comment by tommysitu** [comment]
@larsthorup I'll def check it out this weekend.

**Comment by tommysitu** [comment]
I've added a PR for your repo which should explain it: https://github.com/larsthorup/hoverfly-capture-simulate/pull/1

What you're doing is fine. You just need to make sure HoverflySimulate always starts after HoverflyCapture as the `start` method set the JVM proxy. 

A long term solution would be introducing a method to start Hoverfly without setting the proxy, such as `startWithoutSettingProxy`, but the use case for that is so rare.

**Comment by tommysitu** [comment]
Please close this issue if you're happy :)

**Comment by larsthorup** [comment]
Thank you for the comments! I have merged the PR and cleaned up the code a bit. We will follow this approach.
