### ISSUE TITLE
Allow hoverfly java to use downloaded binary instead of tmp binary

### ISSUE THREAD

**Issue by CorbinLutsch** [SpectoLabs/hoverfly-java#232]
**Is your feature request related to a problem? Please describe.**
Yeah... described below

**Describe the solution you'd like**

Let me explain my problem and then explain the feature. My problem is I am trying to write a Mockito test case to cover the code I wrote with hoverfly java. When my test cases run, they run on a Jenkins server, and my company doesn't give us access to the tmp system folder that hoverfly java wants to write to. I have tried changing the tmp java directory using a java start-up variable and hoverfly java says its writing to the correct directory but then the binary isn't there and it fails. So my suggestion would be to allow us to pass in the location of our binary which we can download off the site and give us the ability to point to that location in the configuration. Otherwise, it will assume to use the tmp binary it creates. 

Or if there's a way to use Mockito without creating an instance of hoverfly java I am all ears. It's hard when there isn't a lot of examples on the internet.

**Comment by tommysitu** [comment]
Hi @CorbinLutsch, an alternative solution would be using `hoverctl` to control the external hoverfly in command line, and then in your Junit tests, you can point Hoverfly JunitRule to use a remote instance: of hoverfly: https://docs.hoverfly.io/projects/hoverfly-java/en/latest/pages/corefunctionality/configuration.html#using-externally-managed-instance

I don't know if that works for your setup. It's worth giving it a try first.

**Comment by tommysitu** [comment]
It's possible to set a different binary location and working directory using the binaryLocation config option

**Comment by CorbinLutsch** [comment]
@tommysitu Very nice. Previously, we had put the instance of Hoverfly in a bean and then autowired it into our class so that it could be mocked in our test cases without starting the binary. This was one solution that worked for us in case anyone else runs into the same issue. Thanks for implementing this though, I'm sure it will come in handy in the future!

**Comment by tommysitu** [comment]
👍  glad you find a way around it.
