### ISSUE TITLE
Update hoverfly to latest (1.3.1 as of now) instead of the currently bundled 1.1.5

### ISSUE THREAD

**Issue by BrainStone** [SpectoLabs/hoverfly-java#246]
**Is your feature request related to a problem? Please describe.**
I would like to use the ``fileBody`` feature introduced in hoverfly 1.3, however since the bundled version is just 1.1.5 it sadly doesn't work.

**Describe the solution you'd like**
The bundled version being bumped to 1.3.1 or whatever the latest version of hoverlfy is at that time.

Additionally it would make sense if hoverfly-java got a bump in regular intervals or at the very least at minor updates of hoverfly (like from 1.2 to 1.3)

**Describe alternatives you've considered**
Only idea I've had in mind would be making a custom build for my own maven. However that runs into issues with my build system which prefers offical builds

**Additional context**
Lastly I believe it would be awesome if the hoverfly version could be printed before starting the server as that would make debugging a lot easier.

**Comment by tommysitu** [comment]
Thanks for the feedback. I was on the verge of releasing a new version: https://github.com/SpectoLabs/hoverfly-java/commits/master. I'm supposed to add support for appending simulation, will get it out soon.

**Comment by BrainStone** [comment]
Hi. Thanks for the response. I checked out the snapshot version and was delighted to discover that it works.

I do have a couple of questions related to it that I'm not sure would be quite suitable for an issue. Is there a place to just quickly chat about those things?

**Comment by tommysitu** [comment]
fixed in v0.14.0
