### ISSUE TITLE
JSON files should have newline character at the end of the file

### ISSUE THREAD

**Issue by Universemul** [SpectoLabs/hoverfly-java#251]
Hi !

I generate stubs with Hoverfly but none have a newline character at the end of the file. 
In Pull Request Github or many other git repo, this is considered a whitespace error.

Maybe the generated file should end with a newline character since that's the POSIX standard or I miss something that could help me to override this behavior with the Java library

Source: http://stackoverflow.com/a/729795/1011988

What do you think?

**Comment by tommysitu** [comment]
It uses `new ObjectMapper().writerWithDefaultPrettyPrinter()` to write the file, there isn't a straightforward way to enable an end of line newline character, any idea?

**Comment by Universemul** [comment]
I don't know if it's really a good idea, but maybe the Hoverfly class can leave the possibility to override the `JSON_PRETTY_PRINTER`.
But by doing this it may add a side effect when reading the simulation ?
