### ISSUE TITLE
no configuration method for listen-on-host functionality

### ISSUE THREAD

**Issue by tejo93** [SpectoLabs/hoverfly-java#276]
I couldnt find a method to set listen-on-host ip in hoverfly java api. is there an alternative? please let me know.

**Comment by tommysitu** [comment]
I wonder what your use case is with this config option in hoverfly java?

**Comment by tejo93** [comment]
I have a docket container in which I have application of hoverfly Java running.
I want to use its api in that container. But from outside the container I cannot access it.

**Comment by tommysitu** [comment]
@tejo93, there is a really useful config method which allows you to add any hoverfly flags not available through the JAVA API, eg.
```
localConfigs().addCommands("-listen-on-host", "0.0.0.0")
```
we should add this to the doc.

**Comment by tommysitu** [comment]
doc updated
