### ISSUE TITLE
No method to delete simulation

### ISSUE THREAD

**Issue by mogronalol** [SpectoLabs/hoverfly-java#43]
When you run it standalone, you have to do `hoverfly.importSimulation(empty())` to clear it. This seems a bit messy, and something along the lines of `hoverfly.deleteSimulation()` would be more expressive.

**Comment by tommysitu** [comment]
@mogronalol How about `hoverfly.reset()`? 
Need to documented clearly that when the user should use it as well.

**Comment by lordofthejars** [comment]
If I understand correctly what is purposed here is create like an _alias_ to `hoverfly.importSimulation(empty())` to a method called `reset` right? I can provide PR as well.

**Comment by lordofthejars** [comment]
This can be closed :)
