### ISSUE TITLE
DSL needs other patch verb

### ISSUE THREAD

**Issue by paul-hammant** [SpectoLabs/hoverfly-java#48]
http://todobackend.com/ has a patch verb usage. 

Would be cool if hoverfly-java did too (hoverfly can capture patch, and simulate it standalone)

**Comment by tommysitu** [comment]
@paul-hammant, that should be easy to do.

**Comment by ph-ms** [comment]
You guys are fast!

**Comment by tommysitu** [comment]
Will be released as v0.3.4
