### ISSUE TITLE
DSL for creating request / response mappings dynamically

### ISSUE THREAD

**Issue by mogronalol** [SpectoLabs/hoverfly-java#6]
Sometimes you may not want to import service data, and instead might want to be able to create it programatically.  This could be done by a DSL which lets you build expected requests and responses.

**Comment by mogronalol** [comment]
There's actually a few things to consider when designing this DSL.  

Do we want to retain the separation between URL components?  So for example, when building we could have something along these lines:

`get("https://www.host.com/path?queryParam=foo").willReturn(...)`

But this abstracts away the separation of url components as stored in the JSON:

```
{
    "scheme" : "http",
    "destination" : "www.host.com",
    "path" : "/path",
    "query" : "?queryParam=foo"
}
```

But maybe this makes sense as it's quite expressive, so internally we could transform things but expose a method which let's us supply things as a full URL.

**Comment by mogronalol** [comment]
I also think the DSL should follow what people would generally do, so @tommysitu idea of starting with a verb, followed by URL makes sense:

`verb(url)`

Then you can optionally do:

`verb(url).withBody(body).withHeader(key, value)`

**Comment by mogronalol** [comment]
@danielbryantuk @tommysitu @benjih

**Comment by tommysitu** [comment]
@mogronalol some good comments there. The design choice to have `service("host.com")` as a top element is to make it more microservices testing oriented, and be able to chain multiple services to build simulation data: 
```
hoverflyRule.simulate(
     service("foo.com")
          .get(path("/firstPath?query=foo")).willReturn(...)
          .post(path("/secondPath").body(body)).willReturn(...)
     .anotherService("bar.com")
           .get(path("/firstPath?query=bar")).willReturn(...)
)
```

**Comment by mogronalol** [comment]
We've gone done this route:

The rule is fluent and hierarchical, allowing you to define multiple service endpoints as follows:

```
hoverflyRule.setSimulation(
    service("www.my-test.com")

        .post("/api/bookings").body("{\"flightId\": \"1\"}")
        .willReturn(created("http://localhost/api/bookings/1"))

        .get("/api/bookings/1")
        .willReturn(success("{\"bookingId\":\"1\"\}", "application/json"))

    .anotherService("www.other-anotherService.com")

        .put("/api/bookings/1").body("{\"flightId\": \"1\"\"}")
        .willReturn(success())

        .delete("/api/bookings/1")
        .willReturn(noContent())
```

The entrypoint for the DSL is `HoverflyDSL.service`.  After calling this you can provide a `method` and `path`, followed by optional request components.
You can then use `willReturn` to state which response you want when there is a match, which takes `responseBuilder` object that you can instantiate directly,
or via the helper class `responseCreators`.
