### ISSUE TITLE
Hoverfly-java

### ISSUE THREAD

**Issue by ipopovsr** [SpectoLabs/hoverfly-java#66]
I am working on a project which includes Hoverfly tool.I have problem to connect the tool with Java Application . The purpose to do that is because i need to use the methods capture and simulate through the Java Application. I will be gratefull if you are going to give me more specific example, how can i do that. In the example on the official site there is some code example but when it doesn't work for me.
Best regards.

**Comment by tommysitu** [comment]
Hi @Igor05051992, could you provide more details on the version of hoverfly-java you are using, and the exception stacktrace you are getting? If you could provide code snippets of your test or how to reproduce the error, we can try troubleshooting it from our end.

**Comment by Igor05051992** [comment]
@tommysitu  to set hoverfly in mode capture and simulate through Java Application can i do that and how?

**Comment by ipopovsr** [comment]
@tommysitu  hoverfly version v0.10.0
                       java version 1.8.0.121

**Comment by tommysitu** [comment]
@ipopovsr Have a look into these tests: https://github.com/SpectoLabs/hoverfly-java/tree/master/src/test/java/io/specto/hoverfly/ruletest
They are also examples of using HoverflyRule. 

Also the latest docs: http://hoverfly-java.readthedocs.io/en/latest/

If you have a test that fails using HoverflyRule, send me the code, and I can have a look.

**Comment by tommysitu** [comment]
Closing this issue as no other information is provided. Please raise a new one if you find specific issue with using hoverfly-java in your application.
