### ISSUE TITLE
Improved Error Message When Starting Hoverfly Twice

### ISSUE THREAD

**Issue by mogronalol** [SpectoLabs/hoverfly-java#82]
When calling `hoverfly.start` a second time (without stopping it), you get a `port already in use` error, as opposed to something more helpful such as `Hoverfly is already running`, or even doing nothing at all.

I'm not sure which of the two options would be best. Does anyone have any suggestions?

**Comment by simomo** [comment]
It looks like I created a new dup issue , again... Sorry about the spam....
"Adding issue number in commit can specify the target issue of your pull request" , obviously, it's not true...
