### ISSUE TITLE
Can't simulate with junit rule where HoverflyConfig proxyLocalHost(true)

### ISSUE THREAD

**Issue by HasseGbg** [SpectoLabs/hoverfly-java#90]
If proxyLocalHost is set to true in HoverflyConfig, http.nonProxyHosts will be set to "" in the Hoverfly class.
If I then try to add a simulation source to the hoverfly instance, the rest call towards the admin port will be intercepted by the hoverfly proxy.

This, for example, will fail immediately:
HoverflyRule.inSimulationMode(classpath("simulation.json"), HoverflyConfig.configs().proxyLocalHost(true));

with:
com.sun.jersey.api.client.UniformInterfaceException: PUT http://localhost:37292/api/v2/simulation returned a response status of 502 Bad Gateway

Because it goes through the hoverfly proxy when trying to reach the admin port.
Instead of setting nonProxyHosts to "", an exception should be added for the admin port.

It would be good to also be able to define ports that are exceptions via HoverflyConfig.

**Comment by tommysitu** [comment]
Hi @HasseGbg, could you let me know which version of hoverfly-java are you using? This problem may have been fixed in the recent releases.

**Comment by HasseGbg** [comment]
@tommysitu I was using 0.3.8. I tested 0.4.4 now and it looks like it's fixed. I should have checked for a newer version first. Thanks!

**Comment by tommysitu** [comment]
No problem. I am closing this issue now.
