### ISSUE TITLE
how to read data from request and put it in response

### ISSUE THREAD

**Issue by sagardloya** [SpectoLabs/hoverfly-java#92]
Hi,
I have a situation where I need to stub SOAP API using hoverfly. I have some data fields in input which should come as it is in output. How can I read the input field from json file and put that in output by creating stub using hoverfly? As of now I get static response for any request. I need response as per mu request (for example lets say if my request contains one of the tag as <amount>10</amount>then my response should also contains <amount>10</amount>. this input amount changes for different users and this should change in response as well while replaying request

**Comment by JohnFDavenport** [comment]
@sagardloya As we say in today's hoverfly Gitter discussion, this is only possible in middleware currently  We have it on our roadmap to provide the necessary underlying support in hoverfly and so I've raised SpectoLabs/hoverfly#520 here to cover that.

**Comment by adisheshaiah** [comment]
@JohnFDavenport this is a very useful requirement as many of the third party responses will have some unique id from request being returned.
Any quick help will be greatly appreciated. 
Thanks in advance.

**Comment by mogronalol** [comment]
@adisheshaiah This is on our roadmap to implement. If you want to try and implement something yourself, then I'd suggest using middleware.

**Comment by JohnFDavenport** [comment]
Closing this as an issue. SpectoLabs/hoverfly#520 is open for comment.

**Comment by adisheshaiah** [comment]
@mogronalol can you please provide with a sample request and python script, which can read from that request and send response.

**Comment by JohnFDavenport** [comment]
There are some examples of using python middleware with SOAP in the Hoverpy documentation here: https://hoverpy.readthedocs.io/en/latest/pages/usage/usage.html
